url: https://greatposterwall.com
host: greatposterwall.com
siteType: gazelle
icon: '<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="11px" height="12px" viewBox="0 0 22 24" enable-background="new 0 0 22 24" xml:space="preserve">  <image id="image0" width="22" height="24" x="0" y="0"    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAYCAMAAADJYP15AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAABVlBMVEUAAAAvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMEvnMH////T/m9bAAAAcHRSTlMAABScbxoq5/nNlouiawwn4/36fQENv7PZH3D85e83GcnmK5OtCcbdOWzyWjjfowdURS3wQ3PcxQ8bYuGdBChjj5rWqqu2ICRMCL0y29cCprcje/v30U/+znJJX/boSPQGEsM6CpX1hBGN4FCw6p41N9CYMAAAAAFiS0dEca8HXOIAAAAHdElNRQflBg8QJipZPSzlAAABIUlEQVQoz13R11bCQBAG4AyCYkGToKImWBAsCAQLKmLsLRbsohKw9zbvf+WWILv+V3u+zJmdnSgKCfga/AGgUcRAY1OwuaW1LdQuOXSoiKhperhTdOjqJhyJYE+vxNBnIJomRvvlLgODSDMUkxmGGccTMvtGqI6O/Sse14kmJ0C+MZWmxRmrrlYsOzlF58PpGaE2N2sk0wbluXmB8wsF5FmkncFesoE1Xg5yXmGcWE2xiyG/xnndZtUbm1vbO+Tg7HJW9yhDzthXD8iheOg1PzomG3dOTs/OL+j3sMely6vrctytZAOsefXGc9R0Mmrmlg0Kd/coxHzgKwAou3V1/bU/BI9PRk2fX5y/t8LrW5Rf+h5yhA2A9fH5VdIK3z9Frr/KLlYZgS4NmAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMS0wNi0xNVQxNjozODo0MiswMDowMN+dGPkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjEtMDYtMTVUMTY6Mzg6NDIrMDA6MDCuwKBFAAAAAElFTkSuQmCC" /></svg>'
asSource: false
asTarget: true
uploadPath: /upload.php
search: 
  path: /torrents.php
  params:
    searchstr: '{imdb}'
    order_by: size
    order_way: desc
    group_results: 1
    action: basic
    searchsubmit: 1
needDoubanInfo: true
targetInfo:
  editionTags:
    10_bit: 10_bit
    2_disc_set: 2_disc_set
    2d_3d_edition: 2d_3d_edition
    2_in_1: 2_in_1
    3d: 3d
    3d_anaglyph: 3d_anaglyph
    3d_full_sbs: 3d_full_sbs
    3d_half_ou: 3d_half_ou
    3d_half_sbs: 3d_half_sbs
    4k_remaster: 4k_remaster
    4k_restoration: 4k_restoration
    director_s_cut: director_s_cut
    dolby_atmos: dolby_atmos
    dolby_vision: dolby_vision
    dual_audio: dual_audio
    english_dub: english_dub
    extended_edition: extended_edition
    extras: extras
    hdr10: hdr10
    hdr10_plus: hdr10plus
    masters_of_cinema: masters_of_cinema
    scene: null
    the_criterion_collection: the_criterion_collection
    theatrical_cut: theatrical_cut
    two_disc_set: 2_disc_set
    remux: null
    rifftrax: rifftrax
    uncut: uncut
    unrated: unrated
    warner_archive_collection: warner_archive_collection
    with_commentary: with_commentary
description:
  selector: '#release_desc'
imdb:
  selector: '#imdb'
mediaInfo:
  selector: 'textarea[name="mediainfo[]"]'
category:
  selector: '#releasetype'
  map:
    movie: '1'
    tv: '3'
    tvPack: '3'
    music: '5'
source:
  selector: '#source'
  map:
    uhdbluray: 'Blu-ray'
    bluray: 'Blu-ray'
    web: 'WEB'
    hdtv: 'HDTV'
    hddvd: HD-DVD
    dvd: 'DVD'
    other: 'Other'
videoCodec:
  selector: '#codec'
  map:
    h264: 'H.264'
    hevc: 'H.265'
    x264: 'x264'
    x265: 'x265'
    h265: 'H.265'
    mpeg2: 'Other'  
    mpeg4: 'H.264'
    vc1: 'Other'
    xvid: xvid
resolution:
  selector: '#resolution'
  map:
    2160p: '2160p'
    1080p: '1080p'
    1080i: '1080i'
    720p: '720p'
    576p: '576p'
    480p: '480p'
format: 
  selector: '#container'
  map:
    mkv: 'MKV'
    mp4: 'MP4'
    avi: 'AVI'
    ts: 'TS'
    wmv: 'WMV'
    vob: 'VOB IFO'
    iso: ISO
    mpg: MPG
    m2ts: 'm2ts'
